version: "3.8"
services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: "npm run watch"
  #   ports:
  #     - 3001:3001
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - user-db

  gateway-db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: gateway
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      # - .dbdata:/var/lib/mysql
      - mysql-data:/var/lib/mysql
      # - ./my.cnf:/etc/mysql/conf.d/my.cnf
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    ports:
      - 3306:3306
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: "10"

volumes:
  mysql-data: {}
        
